name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
          submodules: recursive
          
    - name: set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle

    - name: Create release keystore
      run: keytool -genkeypair -alias your_alias -keyalg RSA -keysize 2048 -validity 10000 -keystore release.jks -storepass aaaaaa -keypass aaaaaaa -dname "CN=Your Name, OU=Your Unit, O=Your Org, L=Your City, S=Your State, C=Your Country"
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleFreeDynamic
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4.6.1
      with:
          name: apk
          path: lemuroid-app/build/outputs/apk/freeDynamic/release/lemuroid-app-free-dynamic-release.apk      
